# Generated by Django 4.2.3 on 2023-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='load time')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
