# Generated by Django 4.2.3 on 2023-07-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='time',
        ),
    ]
